---
- name: Wait for system ready
  hosts: '{{ target }}'
  gather_facts: false
  become: true
  tasks:
    - name: Wait for nodes to become reachable
      wait_for_connection:

- name: Update version
  hosts: '{{ target }}'
  become: true
  gather_facts: false
  roles:
    - neatcoin
